---
collections:
  # Commented out due to internal private hub bug
  # - name: infra.controller_configuration
  # - name: infra.ah_configuration
  # - name: infra.ee_utilities
  # - name: infra.aap_utilities
  # - name: containers.podman
  # Commented out until CI/CD can get fixed
  # - name: ansible.controller
  # - name: awx.awx
  # Commented out due to internal private hub bug
  # - name: infra.eda_configuration
...
