---

controller_validate_certs: false
ah_validate_certs: false
eda_validate_certs: false

ansible_user: "{{ lookup('ansible.builtin.env', 'USER') }}"
ansible_become_password: "{{ sudo_password }}"

aap_setup_containerized: true
controller_license_file: "{{ aap_setup_prep_inv_vars.all.controller_license_file }}"

aap_setup_inst_setup_dir: "{{ aap_setup_prep_setup_dir }}"
aap_setup_prep_setup_dir: "{{ aap_setup_prep_installer_dir }}"
aap_setup_down_type: "setup-bundle"
aap_setup_prep_working_dir: "{{ aap_setup_working_dir | default('/var/tmp') }}"
aap_setup_working_dir: /home/smn/Projects/AAP

# aap_setup_down_offline_token: "{{ offline_token }}"
aap_setup_down_version: 2.5
aap_setup_rhel_version: 9
aap_setup_prep_installer_file: "/home/smn/Downloads/ansible-automation-platform-containerized-setup-bundle-2.5-3-x86_64.tar.gz"
aap_setup_prep_installer_dir: "/home/smn/Projects/AAP/ansible-automation-platform-containerized-setup-bundle-2.5-3-x86_64"
aap_setup_inst_inventory: "{{ aap_setup_prep_installer_dir }}/inventory"

aap_setup_prep_inv_nodes:
  automationcontroller:
    smn-workstation.dapar.me:
  automationeda:
    smn-workstation.dapar.me:
  database:
    smn-workstation.dapar.me:
  automationhub:
    smn-workstation.dapar.me:
  automationgateway:
    smn-workstation.dapar.me:

  # SSO: # not yet implemented
aap_setup_prep_inv_vars:
  all:

    # Ansible
    ansible_connection: local
    ansible_user: "{{ lookup('ansible.builtin.env', 'USER') }}"
    become_method: sudo
    ansible_become_password: "{{ sudo_password }}"

    # Common variables
    postgresql_admin_username: postgres
    postgresql_admin_password: ansible123!

    registry_username: dapar
    registry_password: ansible123!
    registry_auth: false
    bundle_install: true
    controller_license_file: /home/smn/Projects/AAP/ansible-automation-platform-containerized-setup-bundle-2.5-3-x86_64/AAP_License.zip
    bundle_dir: /home/smn/Projects/AAP/ansible-automation-platform-containerized-setup-bundle-2.5-3-x86_64/bundle
    hub_seed_collections: false
    redis_mode: standalone

    # Platform gateway
    gateway_admin_password: ansible123!
    gateway_pg_host: smn-workstation.dapar.me
    gateway_pg_password: ansible123!

    # Automation controller
    controller_admin_password: ansible123!
    controller_pg_host: smn-workstation.dapar.me
    controller_pg_password: ansible123!

    # Automation hub
    hub_admin_password: ansible123!
    hub_pg_host: smn-workstation.dapar.me
    hub_pg_password: ansible123!

    # Event-Driven Ansible controller
    eda_admin_password: ansible123!
    eda_pg_host: smn-workstation.dapar.me
    eda_pg_password: ansible123!

# aap_setup_prep_inv_secrets:

# aap_setup_inst_extra_vars:
...
