---
eda_credentials:
  - name: "hub"
    description: "private automation hub"
    inputs:
      verify_ssl: false
      username: "{{ aap_username }}"
      password: "{{ aap_password }}"
      host:  "{{ aap_hostname | urlsplit('hostname') }}"
    credential_type: "Container Registry"
    credential_type_name: "Container Registry"
    organization: 'Default'
    organization_name: Default
    validate_certs: false

  - name: "Hub Decision Environment Container Registry"
    description: "Hub Decision Environment Container Registry Credentials"
    inputs:
      verify_ssl: false
      username: "{{ aap_username }}"
      password: "{{ aap_password }}"
      host:  "{{ aap_hostname | urlsplit('hostname') }}"
    credential_type: "Container Registry"
    credential_type_name: "Container Registry"
    organization: 'Default'
    organization_name: Default
    validate_certs: false
...