---
eda_credentials:
  - name: hub
    description: 'private automation hub'
    credential_type: 'Container Registry'
    username: "{{ aap_username }}"
    secret: "{{ aap_password }}"
    organization:
      name: 'config_as_code'
    inputs:
      host: "http://smn-workstation.dapar.me"
      verify_ssl: false 
...