---
eda_decision_environments:
  - name: Hub Default Decision Environment
    description: "Hub Default Decision Environment"
    image_url: "{{ aap_hostname | urlsplit('hostname') }}/de-supported-rhel8:latest"
    credential: "Hub Decision Environment Container Registry"
    organization: "Default"
    
  - name: minimal
    description: "my default decision environment"
    image_url: "{{ aap_hostname | urlsplit('hostname') }}/de-minimal-rhel8"
    credential: hub
    organization: config_as_code
...
