---
hub_collection_remotes:
  - name: rh-certified
    token: "{{ cloud_token }}"
    url: https://console.redhat.com/api/automation-hub/content/published/
    auth_url: https://sso.redhat.com/auth/realms/redhat-external/protocol/openid-connect/token
    requirements:
      - microsoft.ad
      - ansible.windows
      - ansible.controller
      - ansible.eda
      - ansible.hub
      - ansible.platform
      - ansible.posix
      - ansible.receptor
      - purestorage.flasharray
      - purestorage.flashblade
      - purestorage.fusion
      - purestorage.pure1
      - fortinet.fortimanager
      - fortinet.fortios
      - fortinet.fortianalyzer
      - fortinet.fortiflexvm
      - fortinet.fortiswitch
      - kubernetes.core
      - hpe.ilo
      - hpe.oneview
      - redhat.rhel_system_roles
      - redhat.satellite
      - redhat.satellite_operations
      - cloud.terraform
      - vmware.vmware
      - vmware.vmware_rest


  - name: validated
    token: "{{ cloud_token }}"
    url: https://console.redhat.com/api/automation-hub/content/validated/
    auth_url: https://sso.redhat.com/auth/realms/redhat-external/protocol/openid-connect/token
    requirements:
      - infra.aap_configuration
      - infra.aap_utilities
      - infra.ah_configuration
      - infra.ansible_rekey_variables
      - infra.controller_configuration
      - infra.eda_configuration
      - infra.ee_utilities
      - cloud.terraform_ops
      - cloud.vmware_ops

  - name: community
    url: https://galaxy.ansible.com/api/
    requirements:
      - infra.ah_configuration
      - infra.controller_configuration
      - infra.aap_utilities
      - infra.ee_utilities
      - containers.podman
      - awx.awx
      - ansible.posix
      - community.docker
      - community.general
      - community.crypto
      - cloud.terraform

hub_collection_repositories:
  - name: rh-certified
    remote: rh-certified
    wait: false
  - name: validated
    remote: validated
    wait: false
  - name: community
    remote: community
    wait: false

hub_configuration_collection_repository_sync_async_retries: 150
...
