---
- name: Playbook to configure ansible automation platform installation
  hosts: all
  connection: local
  vars_files:
    - ../vaults/{{ env }}.yml
  tasks:
    # - name: Include aap_setup_download role
    #   ansible.builtin.include_role:
    #     name: infra.aap_utilities.aap_setup_download

    - name: Include aap_setup_prepare role
      ansible.builtin.include_role:
        name: infra.aap_utilities.aap_setup_prepare

    - name: Fix Preflight regarding os distro if Fedora running
      ansible.builtin.lineinfile:
        path: "{{ aap_setup_prep_installer_dir }}/collections/ansible_collections/ansible/containerized_installer/roles/preflight/tasks/nodes.yml"
        state: present
        regexp: "      - ansible_distribution == 'RedHat'"
        line: "      - ansible_distribution == 'Fedora'"
    #   # when: ansible_facts['os_family'] == "Fedora"

    - name: Fix Preflight regarding version check if Fedora running
      ansible.builtin.lineinfile:
        path: "{{ aap_setup_prep_installer_dir }}/collections/ansible_collections/ansible/containerized_installer/roles/preflight/tasks/nodes.yml"
        state: absent
        regexp: "ansible_distribution_version"
      # when: ansible_facts['os_family'] == "Fedora"

    - name: Ensure AAP_License File is in place
      ansible.builtin.copy:
        src: /home/smn/Projects/AAP/AAP_License.zip
        dest: "{{ controller_license_file }}"
      delegate_to: localhost

    - name: Include aap_setup_install role
      ansible.builtin.include_role:
        name: infra.aap_utilities.aap_setup_install
...
